Implementação da activity de autenticação
Yuri-M-Dias/HealthHelp pull request #12
Opened 2016-11-05 06:22 UTC by clebersa

Esse pull requeste tem por objetivo implementar a activity de autenticação, mas não incluindo a DAO de usuário que fará a busca dos dados no banco de dados. A comunicação com a service, entretanto, é feita normalmente.
Além disso, nesse PR também estão incluídos um esquema de cores seguindo o padrão de material design, novas strings, nome personalizado para o tema das views da nossa aplicação, tratamento de erros e exemplo de uso de EventBus.
A aprovação desse PR vai permitir ao restante do grupo reutilizar algumas coisas.

2016-11-05 06:27 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEV - Implementar a view AutenticacaoActivity conforme protótipo](https://trello.com/c/JxW9aYYl/24-dev-implementar-a-view-autenticacaoactivity-conforme-prototipo)

2016-11-05 17:03 UTC, Yuri-M-Dias requested changes

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> +                    EventBus.getDefault().post(new ExternalDatabaseEvent<Usuario>(new Exception("Usuário e/ou senha não inválidos")));
EventBus não tem um objeto Error que serve para isso?

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="br.ufg.inf.pes.healthhelp.view.AutenticacaoActivity"></activity>
Por quê tirar a tag self-closed?

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> +        new Thread(new Runnable() {
Isso também não é a melhor forma de se fazer isso. Vai acabar com a memória do celular fácil fácil também. Maneiras melhores de lidar com isso:
[Android Service](https://developer.android.com/reference/android/app/Service.html)
[AsyncTask](https://developer.android.com/reference/android/os/AsyncTask.html) <- Essa foi o que usamos no outro projeto, certeza de funcionar pro que precisamos
[Tutorial com vários outros](http://www.vogella.com/tutorials/AndroidBackgroundProcessing/article.html#usage-of-serviceshttp://www.vogella.com/tutorials/AndroidBackgroundProcessing/article.html#usage-of-services)

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/event/ExternalDatabaseEvent.java
> +public class ExternalDatabaseEvent<T> extends DatabaseEvent<T> {
Qual é a diferença entre esse evento e o outro?

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +        autenticacaoService = new AutenticacaoService();
Then again: [Tem como fazer isso de um jeito melhor](https://guides.codepath.com/android/Dependency-Injection-with-Dagger-2)
Não precisamos mudar agora, agora mesmo, mas ainda é uma forma melhor...

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +        findViewById(R.id.botao_login).setOnClickListener(new View.OnClickListener() {
Não é melhor colocar isso no XML da activity, ao invés de fazer pelo código?

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +                    autenticacaoActivity.runOnUiThread(new Runnable() {
Segundo o quinta, usar runOnUiThread é tão ruim quanto usar Goto, mas eu não posso afirmar que encontrei esse problema pra falar uma solução, só que startar uma nova thread assim direto quase certamente não é necessário pra fazer esse tipo de coisa...

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/LocaisAtendimentoActivity.java
> +        locaisAtendimentoView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
Outro evento de click que deveria estar no XML

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/NovoUsuarioActivity.java
> + * Created by cleber on 03/11/16.
Isso daqui não é necessário, de novo. Não preciso saber quem fez a classe, estamos implementando essas code reviews jutamente para não ter que ficar se preocupando com isso. Além disso, quando várias pessoas tiverem tocado numa activity, não é de muita valia essa anotação. Por isso existe o git, e pra ver o blame de uma certa linha é bem mais seguro de te mostrar o que realmente aconteceu do que essa anotação.

2016-11-05 17:03 UTC, Yuri-M-Dias commented on app/src/main/res/layout-land/activity_autenticacao.xml
> +                android:id="@+id/login"
Regra sobre ids: eles são globais para a aplicação. Então é sempre bom colocar um contexto em cada um, pra poder referenciar por fora e saber de qual activity aquilo saiu.

2016-11-06 14:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> +        new Thread(new Runnable() {
@Yuri-M-Dias, esse código é temporário e vai ser substituído por interações com o Firebase que já executam em background. Só coloquei ele aqui porque a DAO ainda não foi implementada.
Ainda assim vc acha que preciso gastar tempo mexendo com isso?

2016-11-06 15:09 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> +                    EventBus.getDefault().post(new ExternalDatabaseEvent<Usuario>(new Exception("Usuário e/ou senha não inválidos")));
Não encontrei documentação sobre esse objeto Error. Você se refere a [AsyncExecutor](http://greenrobot.org/eventbus/documentation/asyncexecutor/)?

2016-11-06 15:11 UTC, clebersa commented on app/src/main/AndroidManifest.xml
> +        <activity android:name="br.ufg.inf.pes.healthhelp.view.AutenticacaoActivity"></activity>
Isso foi feito automático pela IDE em algum momento onde eu defini a classe br.ufg.inf.pes.healthhelp.view.AutenticacaoActivity como launcher. Apesar de não fazer diferença na execução do código, concordo com você que é melhor deixar self-closed.

2016-11-06 15:59 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/event/ExternalDatabaseEvent.java
> +public class ExternalDatabaseEvent<T> extends DatabaseEvent<T> {
A diferença era que um seria utilizado entre DAOs e o outro entre DAO e Activity. Entretanto, acho que dá pra utilizar diferente instâncias do EventBus pra isso. Sendo assim, deixei apenas a classe DatabaseEvent.

2016-11-06 16:01 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +                    autenticacaoActivity.runOnUiThread(new Runnable() {
Resolvido no commit bef5ec2 utilizando ThreadMode.MAIN como atributo da anotação @Subscribe.

2016-11-06 16:09 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +        findViewById(R.id.botao_login).setOnClickListener(new View.OnClickListener() {
Resolvido no commit 0a01d39.

2016-11-06 16:54 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/LocaisAtendimentoActivity.java
> +        locaisAtendimentoView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
Isso foi incluído no commit 2ca68b, que é antes do branch de autenticação, ou seja, já está no master. Além disso, esse PR não tem por objetivo corrigir os problemas da activity de Local de Atendimento. Isso faz parte da outra tarefa, que eu já estou trabalhando, que é https://trello.com/c/PY3riTK7.

2016-11-06 17:00 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/NovoUsuarioActivity.java
> + * Created by cleber on 03/11/16.
Corrigido em 8f7ce14.

2016-11-06 18:41 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +        autenticacaoService = new AutenticacaoService();
Okay. Fica pra próxima.

2016-11-06 18:50 UTC, clebersa commented
Avaliei as mudanças sugeridas e executei a maioria delas, pois algumas não competem a esse PR ou não precisam ser alteradas agora.

2016-11-06 22:27 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +    public void onDatabaseEvent(DatabaseEvent<Usuario> databaseEvent) {
Este método é disparado quando se faz new DatabaseEvent() no buscaPorLogin em UsuarioDAO ?

2016-11-06 23:08 UTC, lucasdeassis approved these changes
uma pergunta sobre database event

2016-11-07 00:41 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> +    public void onDatabaseEvent(DatabaseEvent<Usuario> databaseEvent) {
Não. Ele é disparado quando executa-se um post utilizando o EventBus. No caso do código que está nesse branch, esse método é chamado nessa linha no de UsuarioDAO:
``` java
EventBus.getDefault().post(new DatabaseEvent<>(usuario));
```

2016-11-07 20:23 UTC, Yuri-M-Dias approved these changes

2016-11-07 20:24 UTC, Yuri-M-Dias commented
@clebersa tomei a liberdade de atualizar a PR para resolver o conflito.

2016-11-07 20:24 UTC, merged