Dev home activity
Yuri-M-Dias/HealthHelp pull request #14
Opened 2016-11-09 05:13 UTC by RenanOfugi

Elaboração dos cards da HomeActivity
 * Status: finalizado

2016-11-10 00:25 UTC, Yuri-M-Dias commented
@RenanOfugi Você precisa dar um merge do master para o seu branch para conseguirmos aceitar essa PR.

2016-11-13 21:42 UTC, Yuri-M-Dias requested changes
Tire esses $, por favor.

2016-11-13 21:42 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void OnClick$VisitasMedicas(View view){
O que diabos é esse $? Até onde eu me lembre, caracteres especiais como nomes não funcionam no Java õ_o E mesmo assim, não tem justificativa nenhuma para usar eles.

2016-11-14 14:42 UTC, Yuri-M-Dias requested changes
O desenvolvimento dessa atividade não precisava de pelo menos um exemplo que não fosse hard-coded? Fazer a "activity" é diferente de "fazer o XML", e acho que essa atividade precisa de algo mais completo do que isso.

2016-11-14 14:42 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +        Context context = getApplicationContext();
Essa repetição, falta de padrão em fazer o toast, e tudo mais, não são necessários. Lança uma exceção logo que não fica com esse tipo de firula no código, completamente desnecessário.

2016-11-14 14:42 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/service/MensagemNaoImplementado.java
> +public class MensagemNaoImplementado {
Uma classe inteira de mensagens, para uma só mensagem? Que é parametrizada? Não precisa disso aqui, muito menos no pacote de serviços.

2016-11-14 16:27 UTC, clebersa requested changes

2016-11-14 16:27 UTC, clebersa commented on app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.MAIN" />
A classe que é executada na inicialização da aplicação é a HomeActivity, não a LocaisAtendimentoActivity. Isso deve ser corrigido.

2016-11-14 16:27 UTC, clebersa commented on app/src/main/res/layout/home_activity.xml
> +
Onde está a ActionBar que deveria haver aqui conforme especificado nos protótipos? Falta adicionar isso. Veja as activities relacionadas a local de atendimento pra isso. Você pode simplesmente copiar e colar o código aqui, adequando o que for necessário, claro (ícone de voltar, título e menus).

2016-11-14 16:27 UTC, clebersa commented on app/src/main/res/layout/home_activity.xml
> +            <android.support.v7.widget.CardView
Essa não é uma requisição de mudança, mas sim uma SUGESTÃO.

Em vez de adicionar todos os cards de forma manual no layout, não é melhor definir uma view HealthHelpCard, por exemplo, e modelar um card lá (pode ser até 2 modelos de card, já que um deles tem um botão)? daí você só define os atributos que diferem entre eles. Isso deixaria o código desse XML bem mais simples. Além disso, isso vai contribuir bastante com a exibição dinâmica (baseada no papel do usuário dentro do sistema) dos cards. Essa exibição dinâmica tem a seguinte regra:

- Card de visitas médicas: Todos os usuários podem ver esse card.
- Card de agendas: Secretária e Profissional de saúde podem ver esse card, mas não Paciente.
- Card de Atuações: Secretária e Profissional de saúde podem ver esse card, mas não Paciente.
- Card de Locais de Atendimento: Secretária pode ver esse card, mas não Paciente e Profissional de saúde.

Caso essa mudança não seja feita, a exibição dinâmica deverá ser feita na Activity escondendo os cards ao criar a activity através das IDs deles. Da forma como sugeri, antes de carregar a activity, você vai decidir se mostra um card ou não.

2016-11-14 16:27 UTC, clebersa commented on app/src/main/res/layout/home_activity.xml
> +                    <ImageView
O card não foi projetado conforme o protótipo. Entretanto, como discutido em sala, o protótipo não segue fielmente as recomendações do Material Design e, sendo assim, o projeto final do card pode ter pequenas variações em relação ao protótipo.

Mesmo assim, na minha opinião, o card fica muito grande da forma como ele está projetado agora. Se não for pra fazer como está no protótipo, eu sugiro remover essa imagem exibida no topo do card, deixando apenas o texto.

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/service/MensagemNaoImplementado.java
> +public class MensagemNaoImplementado {
Concordo. Sugiro o Toast ser executado dentro do método onde ele é chamado (agendarVisitasMedicas, visualizarAgenda, etc).

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void visualizarAgenda(View view){
A visualização é feita pra mais de uma agenda. Sendo assim, ```visualizarAgendas```, não ```visualizarAgenda```

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void agendarVisitasMedicas(View view){
Apenas uma visita (agendamento) é feita por vez. A visualização é feita pra mais de uma agenda. Sendo assim, ```agendarVisitaMedica```, não ```agendarVisitasMedicas```.

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void visitasMedicas(View view){
Nome de  função deveria ser com verbo

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void visualizarAtuacao(View view){
Mesma coisa do comentário acima: utilizar plural, pois vai abrir todas as atuações de um Profissional.

2016-11-14 16:27 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +        MensagemNaoImplementado.MostraMensagemNaoImplementado(context, text);
Utilize a própria instância da activity com o `this` como contexto. Coloque a mensagem diretamente como parâmetro. Isso vai evitar criar 2 variáveis extras apenas pra exibir um Toast.

2016-11-14 16:31 UTC, clebersa requested changes

2016-11-14 16:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +        MensagemNaoImplementado.MostraMensagemNaoImplementado(context, text);
A lista de locais de atendimento está implementado sim! Em vez de mostrar esse Toast aqui, crie uma Intent pra LocaisAtendimentoActivity e execute ela.

2016-11-15 22:21 UTC, clebersa commented
Ainda há mudanças que precisam ser feitas, tais como:

- Actionbar deve exibir menus como no protótipo, e o menu de logout deve finalizar a sessão do usuário.
- O layout dos cards deve ser alterado conforme meu comentário.

As demais mudanças são mais relacionadas à qualidade e deveriam ser implementadas também.

2016-11-16 03:36 UTC, RenanOfugi commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +        MensagemNaoImplementado.MostraMensagemNaoImplementado(context, text);
fiz para ficar mais organizado

2016-11-16 03:36 UTC, RenanOfugi commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void agendarVisitasMedicas(View view){
feito

2016-11-16 03:36 UTC, RenanOfugi commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void visualizarAgenda(View view){
feito

2016-11-16 03:36 UTC, RenanOfugi commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
> +    public void visualizarAtuacao(View view){
feito

2016-11-19 13:22 UTC, clebersa requested changes
Além do comentário sobre o método com nome incorreto (que eu vou corrigir agora), as mudanças que ainda precisam ser feitas são:
- Ajustar layout do card.
- Fazer o botão de logout funcionar.
- Remover a classe desnecessária e colocada em lugar incorreto MensagemNaoImplementado.

Além disso, também execute o Reformat Code do Android Studio (Code >  Reformat Code) pra deixar o código formatado corretamente.

2016-11-19 13:22 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/HomeActivity.java
>      public void visitasMedicas(View view){
Esse nome de método não foi corrigido conforme o comentário anterior.

2016-11-22 16:34 UTC, clebersa commented
O logout está funcionando. Falta realizar as outras duas mudanças apenas.

2016-11-25 05:00 UTC, clebersa approved these changes

2016-11-25 05:02 UTC, clebersa commented
Depois de todas as correções, agora dá pra aprovar esse PR. Tive que fazer algumas correções.
Apenas uma coisa não foi feita nesse PR mas que deve ser feita antes da entrega do produto: escala de privilégios, que seria mostrar os cards da home conforme o perfil do usuário. 
No estado atual, eu aprovo esse PR.

2016-11-25 10:22 UTC, Yuri-M-Dias requested changes
Dependência transiente com a SDK 24

2016-11-25 10:22 UTC, Yuri-M-Dias commented on app/build.gradle
> +    compile 'com.afollestad.material-dialogs:core:0.9.1.0'
Isso força a baixar a SDK 24 do android, já disse! Por quê atualizaram de novo? Tem alguma coisa de muito importante nessa versão?

2016-11-25 14:13 UTC, clebersa commented on app/build.gradle
> +    compile 'com.afollestad.material-dialogs:core:0.9.1.0'
Corrigido

2016-11-25 14:25 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [DEV - Implementar a view HomeActivity conforme protótipo](https://trello.com/c/NZqGadHA/23-dev-implementar-a-view-homeactivity-conforme-prototipo)

2016-11-25 15:27 UTC, Yuri-M-Dias approved these changes

2016-11-25 15:27 UTC, merged