Finalização das classes view de Local de Atendimento (Lista, Adição e Edição)
Yuri-M-Dias/HealthHelp pull request #17
Opened 2016-11-11 04:35 UTC by clebersa

Esse pull requeste adiciona código que tem por função padronizar as telas relacionadas a local de atendimento (lista, adição e edição) e deixá-las com um design melhor e funcional.

2016-11-11 04:36 UTC, clebersa commented
Muita coisa pode não ter sido feita da forma mais eficiente, mas dado o prazo do projeto, não dá pra ficar mudando coisa só porque não é a melhor forma de fazer. Espero que a revisão não avalie coisas assim.

2016-11-11 10:24 UTC, Yuri-M-Dias approved these changes
@clebersa ok, mas para aprovar, por favor execute o reformart code no Android Studio. Ele vai re-ordernar os xmls da view e adicionar os espaços necessários pra activity ficar legal de ler. E não vai te custar mais do que 30s pra fazer. Recomendo deixar a opção marcada no dialog de commit do android studio também.
Eu acho que você simplesmente correu pra fazer tudo, e e tem um monte de código que me parece repetido, e lida com datas de uma forma completamente manual que não deveria ser desnecessária. Não vale a pena o tempo que leva pra construir toda essa estrutura, quando podia gastar meia hora pra colocar uma biblioteca no lugar. Mas só isso, de resto tá bom.
E olhe as suas próprias atividades do trello! Você tinha colocado pra fazer essa de periodo de tempo em outra atividade mas fez ela aqui da mesma forma. Claro que teria conflito, não tinha marcado que estava fazendo ela no Trello.

2016-11-11 13:20 UTC, clebersa commented
@Yuri-M-Dias, executei o reformat code. Obrigado pela revisão.
Além disso, sobre as coisas que estão meio repetidas, podemos criar uma tarefa pra executar isso, já que algumas pessoas prefeririam isso em vez de desenvolver algo novo no projeto já que não dominam muito bem a tecnologia.

2016-11-13 21:49 UTC, Yuri-M-Dias requested changes
Aquela classe já tinha sido removida, acho que ela vai dar conflito no Travis por testes que não funcionam... Só isso.

2016-11-13 21:49 UTC, Yuri-M-Dias commented on app/src/androidTest/java/br/ufg/pes/healthhelp/ExampleInstrumentedTest.java
>  import org.junit.Test;
Essa classe foi removida no repositório principal... Recomendo manter essa remoção por enquanto.

2016-11-14 14:11 UTC, clebersa commented
@Yuri-M-Dias, removi a classe que você pediu e ainda fiz o merge com o master pra ter certeza de que tudo estaria sem conflitos. PR pronto pra ser aprovado o/

2016-11-14 14:36 UTC, Yuri-M-Dias approved these changes

2016-11-14 14:36 UTC, merged