Gleibson branch
Yuri-M-Dias/HealthHelp pull request #2
Opened 2016-10-13 23:47 UTC by GleibsonSilva

Por favor aceita ai...

2016-10-26 03:58 UTC, clebersa requested changes
- Qual é mesmo o propósito desse branch? Eu sugeriria pra desenvolver a tarefa "DEV - Finalizar implementação das views LocaisAtendimentoActivity, FormularioLocalAtendimentoActivity e LocalAtendimentoActivity conforme protótipo" do Trello. Caso contrário, um novo branch deverá ser criado para tratar dos problemas que eu cito abaixo.
- O botão de adição está funcionando, mas na minha opinião, ele deveria ir direto pra tela de novo cadastro, não aparecer uma nova opção acima que é a que faz isso. Entretanto, se o grupo achar que assim é melhor, por mim tudo bem. Daí teremos que replicar isso nas outras telas.
- A cor do botão de adição deveria ser verde, conforme o protótipo.
- A tela está com problema de renderização e os itens não estão espaçados/posicionados corretamente. Ver protótipo pra referência.
- A tela de cadastro não tem o botão de finalizar o cadastro e, sendo assim, não salva o local de atendimento. Ver protótipo e diagrama de classes pra referência.

2016-10-27 15:01 UTC, Yuri-M-Dias commented
Só adicionando ao que o Cléber falou: lembrem de dar merge do seu branch local com o master, ou não podemos aceitar a PR.

2016-11-02 19:34 UTC, Yuri-M-Dias commented
@GleibsonSilva e @marcosvsilva Por favor, deem merge com o Master e arrumem o conflito. O mais rápido o possível.

2016-11-05 17:15 UTC, Yuri-M-Dias commented
@GleibsonSilva e a solução dos conflitos?

2016-11-24 21:05 UTC, closed without merging