[REQ] Corrige features pacote 1
Yuri-M-Dias/HealthHelp pull request #25
Opened 2016-11-24 00:54 UTC by Yuri-M-Dias

Contém as mudanças feitas pelo @jeancarlosjc, e corrigidas para o novo formato.

Ainda não estão prontas: PR é apenas para verificar o estado atual.

2016-11-27 19:31 UTC, clebersa requested changes

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                    // Falta um melhor tratamento de erro
Não posta null. Lança uma exceção (como no onCancelled abaixo) qualquer aqui que as views têm (pelo menos as minhas) um método que trata isso.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                        T objetoEncontrado = localSnapshot.getValue(getTipoEntidade());
Onde eu vou encaixar a construção de um objeto complexo (aninhados, porém de diferentes tabelas) aqui? Adicionar um método abstrato que faz isso para que a subclasse implemente pode ser uma solução. Esse método receberia a referência do objeto que está sendo construído e a fonte dos dados (vinda do firebase). Talvez eu precise pensar nisso com mais detalhes, mas na minha cabeça funciona.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                T objetoEncontrado = dataSnapshot.getValue(getTipoEntidade());
Mesma coisa do comentário acima sobre objeto complexo/aninhado.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AgendaDAO.java
> +    public void buscarPeloNome(String nomeAgenda) {
Acho que esse método não é necessário, pois não me lembro de alguma implementação que busca uma agenda por nome, até mesmo porque podem haver agendas com mesmo nome. O importante, e que eu sei que é necessário, é a busca por id.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +            .setValue(objeto);
Porque esse método não tem callback?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AgendaDAO.java
> +    public void inserir(Agenda agenda) {
O superclasse já não toma conta disso?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/ConvenioDAO.java
> +    public void buscarTodos() {
A super classe já não vai implementar esse método e os demais que são básicos? Porque eles tem implementação aqui?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/PacienteDAO.java
> +public class PacienteDAO extends AbstractDAO<Paciente> {
A superclasse já não toma conta da implementação básica?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> -    public void inativar(Usuario usuario) {
O que aconteceu com esse método? Ele foi removido do projeto? (entendo que ele não seria utilizado agora dadas os objetivos da sprint)

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
>      public void buscarPorLogin(final String login, final String senha) {
A implementação dessa DAO vai substituir a implementação abaixo que é stub pela correta, certo?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/PeriodoTempo.java
> +    private List<String> diasSemana;
Isso não deveria ser um array de String, mas sim de DayOfWeek. Já discutimos sobre o armazenamento e recuperação desse dado no/do banco de dados.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/PeriodoTempo.java
> +    public PeriodoTempo(String horaInicio, String horaFim, String dataInicio, String dataFim, List<String> diasSemana) {
Deve-se corrigir o último tipo do último parâmetro.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/PeriodoTempo.java
> +            stringBuilder.append(diasSemana.get(index));
Volta isso aqui pro que estava. Esse toString é utilizado para coisas na view.
```java
stringBuilder.append(diasSemana.get(index).getDisplayName());
```

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +    DayOfWeek(int value, String displayName) {
Porque o private foi removido? Não me lembro se por padrão o Java identifica o construtor de uma enum como privado, mas caso isso não aconteça, o modificador deve permanecer.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +    public static DayOfWeek of(final String dayOfWeek) {
Esse método não é necessário, é? A implementação anterior funcionava corretamente sem ele, tanto pra view quanto pra dao.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AgendaDisponivelActivity.java
> +        List<String>diasSemana = new ArrayList<>();
Como dito em comentários acima, a implementação deve manter DayOfWeek.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> -        EventBus.getDefault().unregister(this);
Porque isso aqui foi removido?

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/PeriodoTempoView.java
>  public class PeriodoTempoView extends LinearLayout {
Esse comentário serve pra classe inteira: reverter o uso de String no lugar de DayOfWeek.

2016-11-27 19:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/PeriodoTempoView.java
> +        for (
Porque esse `for` foi formatado dessa forma? Não está legal.

2016-11-27 21:26 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +    DayOfWeek(int value, String displayName) {
Até onde eu me lembre, ele é redundante. Não tem como um enum ter construtor público.

2016-11-27 21:28 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/PacienteDAO.java
> +public class PacienteDAO extends AbstractDAO<Paciente> {
E toma. Deixei o inserir por falta de conseguir pensar/terminar uma coisa mais genérica dele.

2016-11-27 21:40 UTC, lucasdeassis requested changes

2016-11-27 21:40 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +    public void inserir(T objeto) {
É necessário um ValueListener para inserir, atualizar e remover. Sem ele o evento não seria lançado quando houver qualquer uma dessas operações

2016-11-27 21:40 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AgendaDAO.java
> +                            Log.w(TAG, "agenda não encontrada");
De acordo com o que o Cleber mencionou, lançar exceção aqui

2016-11-27 21:40 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/ConvenioDAO.java
> +                    EventBus.getDefault().post(new DatabaseEvent<>(databaseError));
Lançar exceção, como combinado

2016-11-27 21:40 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                    EventBus.getDefault().post(new DatabaseEvent<>(objetosEncontrados));
Lançar o post do EventBus com a classe DatabaseEvent<T> para este caso é problemático pois ele acionará mais de um método anotado como @subscribe, ja que  a diferenciação de tipo não será feita. Digo, por exemplo, DatabaseEvent<>(String) e DatabaseEvent<>(Agenda) serão considerados como objetos do mesmo tipo. Logo, passe o objetosEncontrados diretamente para o post()

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +            .setValue(objeto);
Eu segui o padrão das outras implementações de DAO. Nenhuma delas tinha callback pra inserir/remover/alterar. Fica sendo uma decisão do que deveria ser retornado quando essas operações acontecem. Vou colocar retornar o objeto que foi inserido por default, então.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                    // Falta um melhor tratamento de erro
Crirei uma ObjetoInexistenteException para deixar isso mais organizado.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                        T objetoEncontrado = localSnapshot.getValue(getTipoEntidade());
Esse era o problema que eu estava tentando resolver ontem. Por isso nos outras métodos de DAO que já tinham alguns objetos mais complexos eu deixei a implementação original.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/ConvenioDAO.java
> +    public void buscarTodos() {
Esses eu esqueci de tirar :disappointed:

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> -    public void inativar(Usuario usuario) {
Eu tirei quanto estava testando o login com o Firebase. colocar de volta.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
>      public void buscarPorLogin(final String login, final String senha) {
Por enquanto. Não deu pra terminar isso ainda. Tava querendo aprovar essa PR, e depois terminar com o UsuarioDAO em outra.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/PeriodoTempo.java
> +    public PeriodoTempo(String horaInicio, String horaFim, String dataInicio, String dataFim, List<String> diasSemana) {
Done

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/PeriodoTempo.java
> +            stringBuilder.append(diasSemana.get(index));
Done

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +    public static DayOfWeek of(final String dayOfWeek) {
Retirado.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AgendaDisponivelActivity.java
> +        List<String>diasSemana = new ArrayList<>();
Done.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> -        EventBus.getDefault().unregister(this);
FirebaseAuth. Voltado.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/PeriodoTempoView.java
>  public class PeriodoTempoView extends LinearLayout {
Done.

2016-11-27 21:46 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/PeriodoTempoView.java
> +        for (
Wow, não faço a menor ideia. Android Studio deve ter formatado isso de uma maneira maluca por alguma razão, mas já voltei também õ_o

2016-11-27 22:23 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                    EventBus.getDefault().post(new DatabaseEvent<>(objetosEncontrados));
Feito.

2016-11-27 23:59 UTC, lucasdeassis approved these changes

2016-11-28 00:31 UTC, clebersa requested changes

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AgendaDAO.java
> +                            Log.w(TAG, "agenda não encontrada");
Na verdade esse método deveria ser removido já que não é exercitado no nosso sistema (exceto testes, provavelmente).

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/AbstractDAO.java
> +                        T objetoEncontrado = localSnapshot.getValue(getTipoEntidade());
Pois é, então acho que é necessário algum tipo de suporte da Abstract pras suas filhas. Assim, em caso de armazenamento e recuperação, as filhas saberiam o que fazer.

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/ConvenioDAO.java
> +    public void buscarTodos() {
Então é só tirar que é sucesso o/

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/PacienteDAO.java
> +                EventBus.getDefault().post(new DatabaseEvent<>("Paciente" + dataSnapshot.getKey().toString()));
Agora isso não tem muito efeito, mas seria melhor retornar uma mensagem indicando o sucesso da inserção, na minha opinião.

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
> -    public void inativar(Usuario usuario) {
Okay. Coloca de novo que é sucesso o/

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/dao/UsuarioDAO.java
>      public void buscarPorLogin(final String login, final String senha) {
Okay.

2016-11-28 00:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/view/AutenticacaoActivity.java
> -        EventBus.getDefault().unregister(this);
Okay

2016-11-28 06:39 UTC, clebersa approved these changes

2016-11-28 17:15 UTC, merged