Atualizaçao de Funcionalidades para o profissional de saúde
Yuri-M-Dias/HealthHelp pull request #3
Opened 2016-10-14 00:08 UTC by rodolphohiroshi

2016-10-26 04:05 UTC, clebersa requested changes
- Corrigir codificação do arquivo.
- Corrigir nome do arquivo para padrão utilizado pelo @Yuri-M-Dias nos arquivos criados por ele em HealthHelp/assets/features/
- Corrigir a sintaxe do seu arquivo, pois ela não parece estar de acordo com a sintaxe definida pelo @Yuri-M-Dias nos nos arquivos criados por ele em HealthHelp/assets/features/

2016-10-27 15:00 UTC, Yuri-M-Dias requested changes
Instale o editorconfig em qualquer que seja a IDE que você usa e tente editar por lá, por favor... O erro de encoding e o fato de ser .features que o Cleber falou também valem. Tem...muitos espaços entre os arquivos aqui na nossa visão. Os nomes também não seguem o padrão dos outros documentos.
Também não parece ter seguido a sintaxe da Gherkin direito, ou sequer feito vários detalhes importantes nos testes.

2016-10-27 22:15 UTC, GleibsonSilva approved these changes

2016-11-02 19:50 UTC, Yuri-M-Dias commented
@rodolphohiroshi ainda não corrigiu os problemas, e temos os mesmos que os da outra PR. NÃO faça isso peo GitHub que ele não vai suportar essa sintaxe, e vai te obrigar a refazer tudo no final. A feature não está documentando nada, parece que foi simplesmente copiada do exemplo e alguns nomes foram alterados. Não está válida para o projeto, muito menos para o Cucumber.

2016-11-13 21:53 UTC, Yuri-M-Dias approved these changes

2016-11-20 04:14 UTC, merged