Cadastros de usuarios features
Yuri-M-Dias/HealthHelp pull request #4
Opened 2016-10-14 00:12 UTC by jeancarlosjc

2016-10-26 04:09 UTC, clebersa requested changes
@jeancarlosjc, aparentemente seu arquivo não segue a mesma sintaxe definida nos arquivos do mesmo tipo criados pelo @Yuri-M-Dias em HealthHelp/assets/features/ . Sendo assim, recomendo a verificação desse aspecto para aprovação desse pull request.

2016-10-27 14:56 UTC, Yuri-M-Dias requested changes
Os arquivos estão como .features, mas deveriam estar com .feature.
Os espaços também tinham que ser respeitados entre os cenários/funcionalidades, porque a legibilidade fica muito ruim desse jeito.
Você também parece que só copiou os dados de um lado pro outro mas não aprofundou nos específicos de nenhum dos requisitos... "Quando eu inserir dados válidos" realmente não vale de muito para ajudar a entender o sistema.

2016-10-27 22:52 UTC, lucasdeassis reviewed
Adicionar cenários de exceção para as funcionalidades.

2016-10-27 22:58 UTC, GleibsonSilva approved these changes

2016-11-02 19:48 UTC, Yuri-M-Dias commented
@jeancarlosjc você não deletou os antigos arquivos .features errados, e essa descrição dos requisitos está muito pouca para sabermos o que devemos implementar. Faltam vários cenários para serem definidos assim, recomendo darem uma lida melhor no documento de requisitos. Pensem nas features como sendo estórias de usuário: você tem que documentar os fluxos principais e os fluxos alternativos que podem acontecer para essa história.

Os arquivos também ainda estão com um espaçamento meio grande demais, não sei como estão formatando isso, mas NÃO recomendo escrever essas features direto no GitHub. Perceba também que os arquivos NÃO são válidos para o Cucumber, não estão utilizando da especificação que está no README desse projeto.

2016-11-05 17:13 UTC, Yuri-M-Dias requested changes
Deu uma melhora significativa na descrição, porém ela anda não está clara. Tem muita coisa genérica, e os passos ainda parecem cópias exatas uns dos outros. Nem falei todos os pontos de todos os arquios porque é exaustivo, mas todos tem os mesmos problemas. Esquemas de cenário não são necessários nesses casos, como eu falei, a maioria nem estão sendo repetidos...

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroProfissionaisdaSaude.feature
> +		3) Não permitir cadastros de pacientes com os mesmos dados.
As duas primeiras restrições não são necessárias e não fazem sentido de descrever no contexto dessa feature

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroProfissionaisdaSaude.feature
> +		Então aparecerá uma mensagem me informando "<mensagem>"
Se a mensgem sempre for a mesma para um dado válido, não é necessário colocar ela como exemplo.

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroProfissionaisdaSaude.feature
> +		E preenchendo <nome>, <profissão>, <numero de conselho regional de saúde>, <email>, <telefone>
Esse "dados válidos" não serve de nada também. Coloque "Quando eu preencher os dados <nome>, ..."

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroProfissionaisdaSaude.feature
> +		Quando eu inserir um campo inválido
Mesma coisa do de cima: "preencher um campo inválido" é muito genérico. Esses requisitos devem ser o mais próximos da realidade o possível, com interações que pensem nos usuários.

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroSecretaria.feature
> +		3) Não permitir cadastros de pacientes com os mesmos dados.
Mesmo problema de restrições desnecessárias

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroSecretaria.feature
> +	Para que eu consiga realizar as operações no sistema.
Quais operações?

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroSecretaria.feature
> +		Quando eu inserir os dados válidos
Genérico

2016-11-05 17:13 UTC, Yuri-M-Dias commented on assets/features/CadastroSecretaria.feature
> +		Então o sistema me informará o campo na qual preenchi de forma inválida, com uma mensagem na tela "<mensagem>"
Substitua esse "com" por um passo "E" em outra linha

2016-11-24 00:51 UTC, Yuri-M-Dias commented
Feature fechada. Será corrigido e terminado em outra PR, feita do branch 'REQ-corrige-features-pacote-1'

2016-11-24 00:51 UTC, closed without merging