Diagramas de classe do pacote 02
Yuri-M-Dias/HealthHelp pull request #5
Opened 2016-10-26 03:46 UTC by clebersa

Nesse pull request estão incluídos os diagramas de classe geral (interações entre view, service e dao), diagrama do pacote dao e diagrama do modelo de dados. Além disso, alguns arquivos de projeto que variam de computador pra computador foram removidos.

2016-10-27 15:09 UTC, Yuri-M-Dias requested changes
- Esses nomes dos diagramas estão bem...estranhos. Cd? Dm?
- Por quê um DAO utilizaria outro DAO? Isso não é tido geralmente como uma boa ideia... O melhor é manter essa regra nos serviços, que podem utilizar de vários DAOs ao mesmo tempo.
- Como passaria um callback entre as classes? Sem o Rx ou Java8, não tem como fazer programação que sequer pareça funcional no Android...
- Essa arquitetura do DAO está absurdamente complexa, sem ter a menor necessidade de fazer isso. Só tente imaginar o tanto de classes que você teria que instanciar para conseguir usar UM dos DAOs dessa forma... Nem todas elas deveriam ter essa complexidade, recomendo revisar isso. Sem contar nos dados inconsistentes com o outro digrama.
- Por quê temos que ter uma sessão realmente? Isso geralmente não é uma boa ideia de se fazer em projetos mobile/iot/android, tem o paradigma "stateless" que resolve os problemas de conexão que provavelmente vamos encontrar se utilizarmos as sessões desse jeito. Acho que o firebase também nem implementa esse tipo de coisa assim.

2016-10-27 23:01 UTC, GleibsonSilva approved these changes

2016-10-27 23:41 UTC, lucasdeassis commented
Na classe de profissional de saúde, mudar o nome do atributo de "crm" para "numeroDeConselho" pois nem todo profissional de saúde teria CRM. Mudar o relacionamento entre Usuário, Profissional e Paciente para herança, sendo o Usuário superclasse de Paciente e Profissional

2016-10-28 20:59 UTC, clebersa commented
Em resposta aos comentários do @Yuri-M-Dias:

- Mudei o nome dos arquivos conforme discutido em sala de aula ontem.
- A utilização de uma DAO por outra permanece conforme discussão em sala de aula ontem. A questão é que essa utilização aconteceria quando operações com objetos aninhados forem efetuadas.
- A classe DatabaseCallback foi removida para dar lugar ao EventBus, como sugerido e discutido em sala de aula ontem.
- Algumas coisas foram simplificadas nas DAOs, mas a estrutura permanece quase a mesma. Além disso, como esclarecido em sala de aula ontem, não existe inconsistência entre os diagramas. As classes são apresentadas em diagramas diferentes por uma questão de objetivo de cada diagrama.
- A sessão não se relaciona com banco de dados. Ela é algo apenas local (no dispositivo) e seria um ponto centralizado para recuperação de informação de autenticação.

Em resposta aos comentários do @lucasdeassis:

- O nome do atributo "crm" foi mudado para "numeroConselho", pouco diferente do sugerido, mas com o mesmo propósito.
- De acordo com discussão posterior à aula com o @lucasdeassis, ficou esclarecida a razão pela qual o relacionamento entre Usuário, Profissional e Paciente é feita por associação. A questão é que um usuário pode ser paciente e também um profissional, podendo exercer a profissão de mais de um profissional. Isso inviabiliza o uso de herança.

2016-10-31 23:21 UTC, lucasdeassis approved these changes

2016-11-02 19:32 UTC, Yuri-M-Dias approved these changes

2016-11-02 19:33 UTC, merged

2016-11-14 14:32 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Elaborar diagrama de classes do Pacote 2](https://trello.com/c/XOfzTBZ5/7-elaborar-diagrama-de-classes-do-pacote-2)