Implementar model
Yuri-M-Dias/HealthHelp pull request #7
Opened 2016-10-27 16:46 UTC by RenanOfugi

* Criado classes modelos e enums
 * Utilização de herança simples, fiquei em duvida se usava abstract...

2016-10-27 22:41 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Convenio.java
> +    String nomeconvenio;
apenas mudar pra nomeConvenio

2016-10-27 22:46 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Profissional.java
> +    private Date ultimoacesso;
mudar para ultimoAcesso. Usar padrão camelcase

2016-10-27 22:48 UTC, lucasdeassis requested changes
Apenas colocar alguns nomes em CamelCase para aprovação.

2016-10-27 23:02 UTC, GleibsonSilva approved these changes

2016-10-30 21:10 UTC, lucasdeassis commented
Adição de atributos e classes para adequar ao diagrama de classe.

2016-11-02 19:41 UTC, Yuri-M-Dias approved these changes
Fora os comentários que eu coloquei, não há nada de errado com essa PR, mas eu não verifiquei os diagramas quanto a corretude. Vou aprovar, mas se quiserem alterar alguma coisa, me avisem antes:
@RenanOfugi e @lucasdeassis

2016-11-02 19:41 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Atuacao.java
> + */
Esse tipo de assinatura é irrelevante para o projeto. Se não tiver uma documentação planejada, é melhor não ter esse tipo de coisa. Na próxima, simplesmente delete ou mude o template da sua IDE pra ficar de acordo.

2016-11-02 19:41 UTC, Yuri-M-Dias commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +public enum DayOfWeek {
Isso já não existe na interface do Java? Por quê replicar aqui, principalmente com os mesmos nomes e menor funcionalidade, já que as classes padrão não vão conseguir entender esses enums?

2016-11-03 02:30 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Atuacao.java
> + */
Não acho tão irrelevante assim. Esse tipo de comentário mostra a autoria do arquivo sem a necessidade de verificar log no git. Além disso, como o @Yuri-M-Dias disse, adicionar algum comentário explicativo à classe seria legal também.

2016-11-03 02:31 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Convenio.java
> +    private String nomeConvenio;
No modelo de dados, esse atributo não se chama "nomeConvenio", mas sim "nome".

2016-11-03 03:37 UTC, clebersa requested changes
Além dos mudanças que eu comentei em algumas partes do código, também sugiro isso aqui para que o PR seja aprovado:
- Implementar a classe `Sessao`.
- Adicionar a lista de `java.time.DayOfWeek` na classe `PeriodoTempo`, pois isso está faltando lá.

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Paciente.java
> +    Convenio convenio;
No modelo de dados, esse atributo "convenio" é privado, não público como colocado aqui.

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Usuario.java
> +    private List<String> telefones;
Porque há duas listas de telefones? Isso não existe no modelo de dados. Lembrar de remover também os métodos get e set.
Além disso, a lista deve ter nome no plural ("emails" e "telefones").

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Usuario.java
> +package br.ufg.inf.pes.healthhelp.model;
Onde está a classe Sessao? Ela se relaciona com a classe Usuario e deve ser implementada pois faz parte do modelo de dados.

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Profissional.java
> +public class Profissional {
Essa classe deve ser abstrata, como pode ser visto no modelo de dados (quando uma classe tem o nome em itálico, isso significa que ela é abstrata).

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Atuacao.java
> +    private Date dataInicioAtuacao;
O nome, de acordo com o modelo de dados, deve ser "dataInicio".

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Atuacao.java
> +    private Date dataFimAtuacao;
O nome, de acordo com o modelo de dados, deve ser "dataFim".

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Agenda.java
> +    private String tempoPadrao;
A variável tempoPadrao é do tipo int, não String.

2016-11-03 03:37 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Usuario.java
> +    private List<String> telefones;
Como o @Yuri-M-Dias disse e eu mencionei no modelo de dados do pacote 1, essa classe já existe no pacote `java.time`: [DayOfWeek](https://docs.oracle.com/javase/8/docs/api/java/time/DayOfWeek.html).

2016-11-03 11:29 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +public enum DayOfWeek {
Existe, mas o android ainda não possui suporte à biblioteca java.time do  Java 8. Como descrito em https://developer.android.com/guide/platform/j8-jack.html, apenas alguns recursos do java 8 são adotados. Logo, quando se tenta usar java.time.DayOfWeek no projeto, o pacote não é encontrado.

2016-11-03 11:44 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Usuario.java
> +package br.ufg.inf.pes.healthhelp.model;
Classe Sessao foi adicionada. Como seria a implementação dos métodos descritos no modelo de dados?

2016-11-03 12:23 UTC, lucasdeassis commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Usuario.java
> +package br.ufg.inf.pes.healthhelp.model;
Implementação atualizada.

2016-11-03 13:39 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Sessao.java
>      public Sessao() {}
O construtor dessa classe deve ser privado, pois ela implementa o padrão de projeto Singleton. Se o construtor for público, outras classes poderão criar instâncias de Sessão, o que não pode acontecer.

2016-11-03 13:39 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Sessao.java
> +            Sessao sessaoSing = new Sessao;
Essa atribuição pode acontecer direito à variável `sessao`. Além disso, o new Sessao não deveria ser seguido de parênteses isso dá erro de compilação?
Sendo assim, essa linha deveria ser:
`sessao = new Sessao();`

2016-11-03 13:39 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Sessao.java
> +            sessaoSing.usuario = null;
Essa instrução deveria ir dentro do construtor da Sessao, mas utilizando a variável sessao, não sessaoSing.

2016-11-03 13:39 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/Sessao.java
> +            Sessao.sessao = sessaoSing;
Pode ser removido pois isso já acontece na primeira linha do `if`

2016-11-03 13:39 UTC, clebersa commented on app/src/main/java/br/ufg/inf/pes/healthhelp/model/enums/DayOfWeek.java
> +public enum DayOfWeek {
Entendi. Obrigado pela explicação, @lucasdeassis. 
Sendo assim, apenas deixe a sua implementação dessa classe um pouco mais elaborada com a mesma interface da classe do java. Você pode implementar ela assim:

``` java
import java.security.InvalidParameterException;

public enum DayOfWeek {

    MONDAY(1, "Segunda"), TUESDAY(2, "Terça"), WEDNESDAY(3, "Quarta"), THURSDAY(4, "Quinta"), SATURDAY(5, "Sexta"), SUNDAY(6, "Sábado");
    private int value;
    private String displayName;

    private DayOfWeek(int value, String displayName) {
        this.value = value;
        this.displayName = displayName;
    }

    public int getValue() {
        return value;
    }

    public String getDisplayName() {
        return displayName;
    }
    public DayOfWeek of(final int dayOfWeek) {
        DayOfWeek dayOfWeekReturn = null;
        for (DayOfWeek dayOfWeekFinder: DayOfWeek.values()) {
            if(dayOfWeekFinder.getValue() == dayOfWeek) {
                return dayOfWeekFinder;
            }
        }
        if(dayOfWeekReturn == null) {
            throw new InvalidParameterException("Unable to convert to a DayOfWeek");
        }

        return dayOfWeekReturn;

    }


}
```

2016-11-03 13:51 UTC, clebersa requested changes
Adicionei alguns comentários para pequenas mudanças e ainda adicionei um outro comentário relacionado à classe DayofWeek

2016-11-03 20:47 UTC, lucasdeassis commented
Enum DayOfWeek e Classe sessão atualizados de acordo com comentários.

2016-11-03 21:17 UTC, clebersa approved these changes

2016-11-03 21:19 UTC, lucasdeassis approved these changes

2016-11-03 21:20 UTC, merged